; PlatformIO Project Configuration File

;install instructions at the end!! works on Linux and wondows


;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;CONFIRMED WORKING WITH PLATFORMIO 6.1.0 and Arduino 2.3.0
;UPDI ATTINY3226 analog bridge 2026
 

; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATtiny3226]
[platformio]
; Default build target
default_envs = Upload_UPDI

[env]
platform = atmelmegaavr
board = ATtiny3226
framework = arduino
build_src_filter = +<main.cpp>


; Clock frequency in [Hz]
board_build.f_cpu = 20000000L
; Oscillator type (internal or external)
board_hardware.oscillator = internal

; Unflag build flags
build_unflags =
; Extra build flags
build_flags =

lib_deps =
    https://github.com/Networking-for-Arduino/EthernetENC.git
    adafruit/Adafruit ADS1X15@^2.5.0

; Monitor port is auto detected. Override here
;monitor_port =
; Serial monitor baud rate
monitor_speed = 57600


; Run the following command to upload with this environment
; pio run -e Upload_UPDI -t upload
[env:Upload_UPDI]

upload_flags =
    --tool
    uart
    --device
    $BOARD_MCU
    --uart
    $UPLOAD_PORT
    --clk
    $UPLOAD_SPEED
upload_command = pymcuprog write --erase $UPLOAD_FLAGS --filename $SOURCE
;ATTENTION: you hve to install pymcuprog and the driver for you programming adapter manually: pip install pymcuprog

[env:ADC_TEST]
extends = env:ATtiny3226
build_src_filter = +<adc-test.cpp> -<main.cpp>
upload_flags =
    --tool
    uart
    --device
    $BOARD_MCU
    --uart
    $UPLOAD_PORT
    --clk
    $UPLOAD_SPEED
upload_command = pymcuprog write --erase $UPLOAD_FLAGS --filename $SOURCE




